### ISSUE TITLE
Nonexistent arguments used in .launch files

### ISSUE THREAD

**Issue by Dangield** [pal-robotics/tiago_navigation#10]
Some launch files from **_tiago_2dnav_** package pass **_base_type_** argument while including launches from **_pal_navigation_cfg_tiago_** package. Unfortunately, launches from the second mentioned package does not need this argument, which causes errors during launching. This changes were included in commit [cfbb0e3012620266e0e05e7b46082e66dc27cd2b](https://github.com/pal-robotics/tiago_navigation/commit/cfbb0e3012620266e0e05e7b46082e66dc27cd2b#diff-7c60c5f24de2c45ef053bf890f737ed45e24eff25109c4d788360ebc89789bc8). Files affected are:

- localization.launch
- move_base.launch
- state_machine.launch

**Comment by saikishor** [comment]
Hello @Dangield!

Thank you for showing interest in our TIAGo's simulation. We have received your query and we will try to fix the issue at the earliest. Thank you for reporting the issue.

Best Regards,
PAL Robotics Team.

**Comment by saikishor** [comment]
@Dangield Thanks for bringing the issue to our notice. We have just fixed the issue from our end. You should have the fix updated here in our GitHub by tomorrow morning. Please do test it and let us know if this fixes the issue you have pointed out.

Thank you,

Best Regards,
PAL Robotics Team.

**Comment by Dangield** [comment]
@saikishor Thank you for the response. The issue seems to be fixed and launches now run without errors.

Best regards,
Daniel Giełdowski

**Comment by saikishor** [comment]
@Dangield Thanks a lot for confirming. Enjoy the simulation with our TIAGo.

Best Regards,
PAL Robotics Team.
