### ISSUE TITLE
public FootprintLayer implementation

### ISSUE THREAD

**Issue by v4hn** [pal-robotics/tiago_navigation#6]
The `costmap_2d` configurations in this package include a [FootprintLayer](
https://github.com/pal-robotics/tiago_navigation/blob/indigo-devel/tiago_2dnav/config/base/common/global_costmap.yaml#L32), but the implementation seems to be provided only as a binary blob in tiago's setup in the package `pal-erbium-costmap-2d`.

It is not part of upstream [navigation](https://github.com/ros-planning/navigation) and I can't find a pull-request or fork by pal that implements it.

This is an actual problem because we had to fix a bug in the navigation stack and compile it ourselves...

**Comment by procopiostein** [comment]
@v4hn if you are using an upstream implementation of the navigation stack, you can remove the footprintLayer from the costmaps configuration.
This layer was deprecated after we forked from upstream, that's why you cannot find it: https://github.com/ros-planning/navigation/issues/289

**Comment by v4hn** [comment]
Ah, that explains it of course, and yes, we proceeded by simply removing it, but I wanted to mention it somewhere. :)

Still, your fork is not yet publicly available as far as I know which is not helpful.
