### ISSUE TITLE
Clearing costmap to unstuck but oscillating over and over

### ISSUE THREAD

**Issue by mydansun** [pal-robotics/tiago_navigation#7]
Hi

I am a student who is learning to use TIAGo. When I perform automatic navigation on my world in the simulator, the clearing costmaps are executed multiple times, and the console will output **aborting because of oscillating over and over**. This error makes automatic navigation is difficult to go on.

I don't know if it's correct to post this question here. I would be very happy if anyone can give me some help. 👍 

Thanks

**Comment by v-lopez** [comment]
Hi @mydansun,

Could you give us more information? What simulation world are you using, and map? Could you please record a video or a rosbag so we can examine it?

Also, are you using tiago as part of a University class? Could we know which University?

**Comment by mydansun** [comment]
Hi @v-lopez 

Thank you very much for your help! :smiley: 

I uploaded a video to the YouTube, here is the link. [https://youtu.be/jwnv88K4rzo](https://youtu.be/jwnv88K4rzo)

I created my own world and I put all files in [https://drive.google.com/open?id=1T_j2_Sz4Y-52Lq2Uh8xXcpCxCST3ii4e](https://drive.google.com/open?id=1T_j2_Sz4Y-52Lq2Uh8xXcpCxCST3ii4e)

The errors from the console
```
[ WARN] [1549284455.615024826, 456.864000000]: Control loop missed its desired rate of 10.0000Hz... the loop actually took 0.8200 seconds
[ WARN] [1549284514.645121572, 481.964000000]: Clearing costmap to unstuck robot (0.000000m).
[ WARN] [1549284538.701306665, 492.164000000]: Clearing costmap to unstuck robot (3.000000m).
[ WARN] [1549284562.956234813, 502.464000000]: Clearing costmap to unstuck robot (1.500000m).
[ WARN] [1549284587.197619593, 512.764000000]: Clearing costmap to unstuck robot (5.500000m).
[ERROR] [1549284611.427371119, 523.064000000]: Aborting because the robot appears to be oscillating over and over. Even after executing all recovery behaviors
```

Some people suggested that I set limits to acceleration, but until now I have not modified any of TIAGo package files, they are all cloned from git.

**Comment by v-lopez** [comment]
Could you try reverting this change?
https://github.com/pal-robotics/tiago_navigation/commit/edba246c33810f337ae3c6ec05ceb1501e010026

Increase the yaw goal tolerance to 1 and see if it still happens.

**Comment by mydansun** [comment]
Hi, @v-lopez 

Thank you so much! I tried to revert this change. After executing multiple Clearing CostMap actions, the robot finally reaches the target point. However, is it possible to reduce the number of Clearing CostMap actions (or the reason is that it is not easy to clear them?), because it makes the robot rotate many times at the destination point, the whole process does not look very smooth.

Here is the output of console
```
[ WARN] [1549295129.259424944, 434.671000000]: Clearing costmap to unstuck robot (0.000000m).
[ WARN] [1549295149.754330828, 444.971000000]: Clearing costmap to unstuck robot (3.000000m).
[ WARN] [1549295170.646792301, 455.271000000]: Clearing costmap to unstuck robot (1.500000m).
[ INFO] [1549295179.124615374, 459.471000000]: TrajectoryController: Goal reached with distance 0.00, 0.02 (od = 0.98); sending zero velocity
[ WARN] [1549295319.507056551, 529.874000000]: Control loop missed its desired rate of 10.0000Hz... the loop actually took 0.8830 seconds
[ WARN] [1549295353.365360173, 546.574000000]: Clearing costmap to unstuck robot (0.000000m).
[ WARN] [1549295373.745282385, 556.875000000]: Clearing costmap to unstuck robot (3.000000m).
[ INFO] [1549295378.993481574, 559.474000000]: TrajectoryController: Goal reached with distance 0.02, 0.02 (od = 0.97); sending zero velocity
```

**Comment by mydansun** [comment]
The oscillating problem reappears when trying to move again. It seems that the obstacle has not been successfully removed in the local costmap.
![Screenshot from 2019-02-04 17-19-25.png](https://i.loli.net/2019/02/05/5c5874ae560d3.png)

**Comment by mydansun** [comment]
I also tried to remove temporary obstacles that were not recorded on the map, and then both the robot and the planner worked fine in most of the time. It seems that these temporary obstacles make the robot confused.

**Comment by procopiostein** [comment]
The clearing behaviour seems to be working just fine. In the video you sent, around time 1:30 you can see that the costmap is cleared. 

The problem here is unrelated to the recovery behaviours, the robot reaches the tolerance in xy but is not converging to the desired orientation. As you mentioned, you may try to reduce angular acceleration and/or velocity. Increasing the yaw tolerance may also help, but you may not end up facing the desired direction.

The effect temporary obstacles would have is in the localisation accuracy. If you are not seeing the robot wrongly localised, it is unrelated to your problem.

**Comment by mydansun** [comment]
Hi, @procopiostein 

Thank you so much, I tried to reduce the `max_acceleration` and `yaw_goal_tolerance` and the robot worked fine!
