### ISSUE TITLE
TIAGO forgets some obstacles after turning

### ISSUE THREAD

**Issue by mydansun** [pal-robotics/tiago_navigation#9]
Hi Team,

I found a problem of navigation with rgbd obstacle detection. Suppose TIAGO is now facing a table, and then he starts to turn. During the turning, this table will be cleared from the costmap. But in the simulator, turning does not cause obstacles to be cleared in the costmap unless they are actually removed in Gazebo. Could anyone give me a hint about this by any chance? Thank you so much!

**Comment by procopiostein** [comment]
Sorry, it is not clear if the problem you have is in the simulation or with a real robot.

Regarding the behaviour you describe in the sim, isn't it what you would expect? as long as the obstacle is still there it will still be in the costmap?

**Comment by mydansun** [comment]
@procopiostein 
Hello,

This problem happens on the real robot.  There is a long obstacle in front of the robot. When TIAGO turns, part of the obstacle previously marked by the RGBD camera is cleared, causing the navigation algorithm to think that there is a path available. There is no such problem in the simulator.

![test1](https://user-images.githubusercontent.com/8871143/76334058-700d2380-62ea-11ea-9610-0626ce559906.gif)

**Comment by procopiostein** [comment]
thanks for the feedback @mydansun .
this repo is only used for public simulations and it will differ from the packages you have if you own a robot.
the best way to address this issue is to open a ticket in PAL Robotics support. do you have access to it?

**Comment by mydansun** [comment]
@procopiostein 
Thanks for your reply. I will ask for someone to open a support ticket. I disable the RGBD camera from clearing obstacles in the costmap so it is only used to mark. Then, it seems to work fine now, but I think this should not be a perfect solution.

**Comment by procopiostein** [comment]
no, because eventually you will have parts of the costmap that remain with noise. the problem here seems to be in the field of view, where no measurements are being treated as free measurements.
please, be exhaustive in the info provided in the ticket (your video, the config you were using, any config you changed, and a rosbag of this situation with the camera pointcloud and tf would be very helpful)
